version: "2"
services:
  app:
    container_name: login-microservice
    image: mamtabhardwaj12/login-microservice
    restart: always
    build: .
    ports:
      - "8085:8085"
    links:
      - mongo
  mongo:
    container_name: login-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"

